### ISSUE TITLE
Real world hardware tests round one

### ISSUE THREAD

**Issue by c-x-berger** [BHSSFRC/3494_2019_repo#12]
Exciting times we live in! Basically all the hardware has finished version one, so we'll use this issue to track which systems have been tested on metal.

- [X] Drivetrain (see also #1)
  - I mean, it drives. The diagnostic features being done by @brownkat6 are still WIP and pretty much unused.
- [X] Climber (see also #2, #10)
  - Not much to test. It does the thing.
  - Auto climbing will need its own on-metal testing (but this hasn't even been programmed yet so :man_shrugging:.) 
- [x] Hatch manipulator (see also #4)
  - [X] Eject hatches from velcro
  - [X] Slap the floor
  - [x] Center rod
- [x] Cargo manipulator (see also #3)
- [x] Cargo arm (see also #3 and d2c7ac1ba0353d0ce95cb714a0cf75ca3e0edea4)
  - [X] Braking system done
  - [x] Motors ~~are totally untested~~ have been tested
